sudo: required
services:
  - docker

before_install:
  - docker build -t zakidr789/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zakidr789/react-test npm test -- --coverage

after_success:
  - docker build -t zakidr789/multi-client ./client
  - docker build -t zakidr789/multi-nginx ./nginx
  - docker build -t zakidr789/multi-server ./server
  - docker build -t zakidr789/multi-worker ./worker
# Log in to the docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push zakidr789/multi-client
  - docker push zakidr789/multi-nginx
  - docker push zakidr789/multi-server
  - docker push zakidr789/multi-worker
